INSERT INTO `MOVEMENT_SPEC` (`FIELD_NAME`,`FIELD_LENGTH`,`FIELD_POSITION`,`FIELD_TYPE`,`FIELD_MAPPER`)
VALUES ('RECORD CODE', 3, 1, 'String', 'recordCode'),
       ('CLIENT TYPE', 4, 2, 'String', 'clientType'),
       ('CLIENT NUMBER', 4, 3, 'String', 'clientNumber'),
       ('ACCOUNT NUMBER', 4, 4, 'String', 'accountNumber'),
       ('SUBACCOUNT NUMBER', 4, 5, 'String', 'subAccountNumber'),
       ('OPPOSITE PARTY CODE', 6, 6, 'String', 'oppositePartyCode'),
       ('PRODUCT GROUP CODE', 2, 7, 'String', 'productGroupCode'),
       ('EXCHANGE CODE', 4, 8, 'String', 'exchangeCode'),
       ('SYMBOL', 6, 9, 'String', 'symbol'),
       ('EXPIRATION DATE', 8, 10, 'Date', 'expirationDate'),
       ('CURRENCY CODE', 3, 11, 'String', 'currencyCode'),
       ('MOVEMENT CODE', 2, 12, 'String', 'movementCode'),
       ('BUY SELL CODE', 1, 13, 'String', 'buySellCode'),
       ('QUANTITY LONG SIGN', 1, 14, 'String', 'quantityLongSign'),
       ('QUANTITY LONG', 10, 15, 'Decimal', 'quantityLong'),
       ('QUANTITY SHORT SIGN', 1, 16, 'String', 'quantityShortSign'),
       ('QUANTITY SHORT', 10, 17, 'Decimal', 'quantityShort'),
       ('EXCH/BROKER FEE/DEC', 12, 18, 'Decimal', 'exchBrokerFee'),
       ('EXCH/BROKER FEE D C', 1, 19, 'String', 'exchBrokerFeeDC'),
       ('EXCH/BROKER FEE CUR CODE', 3, 20, 'String', 'exchBrokerFeeCurCode'),
       ('CLEARING FEE / DEC', 12, 21, 'Decimal', 'clearingFee'),
       ('CLEARING FEE D C', 1, 22, 'String', 'clearingFeeDC'),
       ('CLEARING FEE CUR CODE', 3, 23, 'String', 'clearingFeeCurCode'),
       ('COMMISSION', 12, 24, 'Decimal', 'commission'),
       ('COMMISSION D C', 1, 25, 'String', 'commissionDC'),
       ('COMMISSION CUR CODE', 3, 26, 'String', 'commissionCurCode'),
       ('TRANSACTION DATE', 8, 27, 'Date', 'transactionDate'),
       ('FUTURE REFERENCE', 6, 28, 'String', 'futureReference'),
       ('TICKET NUMBER', 6, 29, 'String', 'ticketNumber'),
       ('EXTERNAL NUMBER', 6, 30, 'String', 'externalNumber'),
       ('TRANSACTION PRICE / DEC', 15, 31, 'Decimal', 'transactionPrice'),
       ('TRADER INITIALS', 6, 32, 'String', 'traderInitials'),
       ('OPPOSITE TRADED ID', 7, 33, 'String', 'oppositeTradeId'),
       ('OPEN CLOSE CODE', 1, 34, 'String', 'openCloseCode');
